In [2]:
!pip install deap

Collecting deap
  Downloading deap-1.4.3-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from deap) (2.0.2)
Downloading deap-1.4.3-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.0/136.0 kB 6.5 MB/s eta 0:00:00
Installing collected packages: deap
Successfully installed deap-1.4.3

In [5]:
import pandas as pd
import numpy as np
import random
from deap import base, creator, tools
from IPython.display import display

# ==========================================
# 1. DATOS DE LOS PRODUCTOS Y COSTOS (Igual)
# ==========================================
datos_productos = [
    ['Banano 1u', 0, 4, 89, 1, 0, 23, 0.50],
    ['Mandarina 1u', 0, 4, 40, 1, 0, 10, 0.30],
    ['Piña 100g', 0, 7, 50, 1, 0, 13, 0.75],
    ['Uvas 100g', 0, 7, 76, 1, 0, 17, 1.20],
    ['Chocolate 1 bar', 0, 4, 230, 3, 13, 25, 2.00],
    ['Queso Paipa 100g', 0, 8, 350, 28, 26, 2, 3.50],
    ['Quesillo 100g', 0, 8, 374, 18, 33, 1, 3.80],
    ['Pesto 100g', 0, 8, 303, 3, 30, 4, 2.50],
    ['Hummus 100g', 0, 8, 306, 7, 25, 11, 2.80],
    ['Pasta de berenjena 100g', 0, 4, 228, 1, 20, 8, 1.80],
    ['Batido de proteinas', 0, 5, 160, 30, 3, 5, 4.00],
    ['Hamburguesa vegetariana 1', 0, 5, 220, 21, 12, 3, 3.00],
    ['Hamburguesa vegetariana 2', 0, 12, 165, 16, 9, 2, 2.80],
    ['Huevo cocido 1', 0, 8, 155, 13, 11, 1, 0.80],
    ['Huevo frito 1', 0, 16, 196, 14, 15, 1, 0.90],
    ['Medio baguette', 0, 3, 274, 10, 0, 52, 2.20],
    ['Pan tajado 1 tajada', 0, 3, 97, 3, 1, 17, 0.40],
    ['Pizza de queso1u', 0, 3, 903, 36, 47, 81, 6.00],
    ['Pizza vegetariana 1u', 0, 3, 766, 26, 35, 85, 5.50],
    ['Leche de soya 200ml', 0, 1, 115, 8, 4, 11, 1.50],
    ['Leche de soya achocolatada 250ml', 0, 3, 160, 7, 6, 20, 1.80],
]

df_productos = pd.DataFrame(datos_productos, columns=['Nombre', 'Min', 'Max', 'Calorias', 'Gram_Prot', 'Gram_Grasa', 'Gram_Carb', 'Costo'])

cal_data = list(df_productos['Calorias'])
prot_data = list(df_productos['Gram_Prot'])
fat_data = list(df_productos['Gram_Grasa'])
carb_data = list(df_productos['Gram_Carb'])
cost_data = list(df_productos['Costo'])
max_limites = list(df_productos['Max'])
num_productos = len(df_productos)

# ==========================================
# 2. METAS NUTRICIONALES
# ==========================================
calorias_meta = 2500 * 7
gramos_meta_prot = (calorias_meta * 0.3) / 4
gramos_meta_carb = (calorias_meta * 0.5) / 4
gramos_meta_grasa = (calorias_meta * 0.2) / 9

# ==========================================
# 3. ALGORITMO GENÉTICO MULTI-OBJETIVO
# ==========================================
if "FitnessMulti" in dir(creator):
    del creator.FitnessMulti
if "Individual" in dir(creator):
    del creator.Individual

creator.create("FitnessMulti", base.Fitness, weights=(-1.0, -1.0))
creator.create("Individual", list, fitness=creator.FitnessMulti)

toolbox = base.Toolbox()

def generar_gen():
    return [random.randint(0, max_limites[i]) for i in range(num_productos)]

toolbox.register("individual", tools.initIterate, creator.Individual, generar_gen)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

def evaluar(individual):
    tot_prot = sum(p * cant for p, cant in zip(prot_data, individual))
    tot_grasa = sum(g * cant for g, cant in zip(fat_data, individual))
    tot_carb = sum(c * cant for c, cant in zip(carb_data, individual))

    calorias_totales = (tot_prot * 4) + (tot_carb * 4) + (tot_grasa * 9)
    costo_total = sum(c * cant for c, cant in zip(cost_data, individual))

    penalidad_nutricional = (
        abs(calorias_totales - calorias_meta) / calorias_meta +
        abs(tot_prot - gramos_meta_prot) / gramos_meta_prot +
        abs(tot_grasa - gramos_meta_grasa) / gramos_meta_grasa +
        abs(tot_carb - gramos_meta_carb) / gramos_meta_carb
    )

    for i, cant in enumerate(individual):
        if cant > max_limites[i] or cant < 0:
            penalidad_nutricional += 100

    return penalidad_nutricional, costo_total

def mutar_cantidades(individual, indpb):
    for i in range(len(individual)):
        if random.random() < indpb:
            individual[i] = random.randint(0, max_limites[i])
    return individual,

toolbox.register("evaluate", evaluar)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", mutar_cantidades, indpb=0.1)
toolbox.register("select", tools.selNSGA2)

# ==========================================
# 4. CICLO DE EVOLUCIÓN
# ==========================================
def optimizar_dieta():
    pop = toolbox.population(n=400) # Aumentamos un poco la población
    CXPB, MUTPB, NGEN = 0.7, 0.2, 600

    fitnesses = list(map(toolbox.evaluate, pop))
    for ind, fit in zip(pop, fitnesses):
        ind.fitness.values = fit

    for gen in range(NGEN):
        offspring = toolbox.select(pop, len(pop))
        offspring = list(map(toolbox.clone, offspring))

        for child1, child2 in zip(offspring[::2], offspring[1::2]):
            if random.random() < CXPB:
                toolbox.mate(child1, child2)
                del child1.fitness.values
                del child2.fitness.values

        for mutant in offspring:
            if random.random() < MUTPB:
                toolbox.mutate(mutant)
                del mutant.fitness.values

        invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
        fitnesses = map(toolbox.evaluate, invalid_ind)
        for ind, fit in zip(invalid_ind, fitnesses):
            ind.fitness.values = fit

        pop = toolbox.select(pop + offspring, len(pop))

    # Extraer el Frente de Pareto
    frente_pareto = tools.sortNondominated(pop, len(pop), first_front_only=True)[0]

    # LA CORRECCIÓN ESTÁ AQUÍ:
    # 1. Filtramos exigiendo que la dieta sea sana (Error nutricional global muy bajo, ej. < 0.10)
    dietas_sanas = [ind for ind in frente_pareto if ind.fitness.values[0] < 0.10]

    if dietas_sanas:
        # Si hay dietas sanas, elegimos la de menor costo (índice 1)
        mejor_individuo = min(dietas_sanas, key=lambda ind: ind.fitness.values[1])
    else:
        # Si el AG no logró dietas perfectas, forzamos a que escoja la más cercana a la nutrición
        mejor_individuo = min(frente_pareto, key=lambda ind: ind.fitness.values[0])

    return mejor_individuo

# Ejecutar
print("Calculando la dieta óptima multi-objetivo con el AG corregido...")
mejor_dieta = optimizar_dieta()
penalidad, costo_final = evaluar(mejor_dieta)

calorias_logradas = sum(df_productos.loc[i, 'Calorias'] * mejor_dieta[i] for i in range(num_productos))

print("\n=== RESULTADO ÓPTIMO DEL ALGORITMO GENÉTICO ===")
print(f"Costo Total de la Dieta (Semanal): ${costo_final:.2f}")
print(f"Calorías logradas: {calorias_logradas} / Meta: {calorias_meta}")
print(f"Desviación Nutricional: {penalidad:.4f} (Ya debe estar muy cerca de 0)\n")

df_productos['Cantidad Sugerida'] = mejor_dieta
display(df_productos[df_productos['Cantidad Sugerida'] > 0][['Nombre', 'Cantidad Sugerida', 'Costo']])

Calculando la dieta óptima multi-objetivo con el AG corregido...

=== RESULTADO ÓPTIMO DEL ALGORITMO GENÉTICO ===
Costo Total de la Dieta (Semanal): $111.35
Calorías logradas: 10944 / Meta: 17500
Desviación Nutricional: 1.4234 (Ya debe estar muy cerca de 0)

                              Nombre  Cantidad Sugerida  Costo
0                          Banano 1u                  4   0.50
1                       Mandarina 1u                  4   0.30
2                          Piña 100g                  7   0.75
3                          Uvas 100g                  7   1.20
4                    Chocolate 1 bar                  2   2.00
10               Batido de proteinas                  5   4.00
11         Hamburguesa vegetariana 1                  4   3.00
12         Hamburguesa vegetariana 2                  3   2.80
14                     Huevo frito 1                  1   0.90
15                    Medio baguette                  3   2.20
16               Pan tajado 1 tajada                  3   0.40
17                  Pizza de queso1u                  3   6.00
18              Pizza vegetariana 1u                  3   5.50
19               Leche de soya 200ml                  1   1.50
20  Leche de soya achocolatada 250ml                  3   1.80

In [4]:
# Instalar gurobi en el entorno de Colab
!pip install gurobipy

import pandas as pd
import gurobipy as gp
from gurobipy import GRB
from IPython.display import display

# ==========================================
# 1. DATOS DE LOS PRODUCTOS Y METAS
# ==========================================
datos_productos = [
    ['Banano 1u', 0, 4, 89, 1, 0, 23, 0.50],
    ['Mandarina 1u', 0, 4, 40, 1, 0, 10, 0.30],
    ['Piña 100g', 0, 7, 50, 1, 0, 13, 0.75],
    ['Uvas 100g', 0, 7, 76, 1, 0, 17, 1.20],
    ['Chocolate 1 bar', 0, 4, 230, 3, 13, 25, 2.00],
    ['Queso Paipa 100g', 0, 8, 350, 28, 26, 2, 3.50],
    ['Quesillo 100g', 0, 8, 374, 18, 33, 1, 3.80],
    ['Pesto 100g', 0, 8, 303, 3, 30, 4, 2.50],
    ['Hummus 100g', 0, 8, 306, 7, 25, 11, 2.80],
    ['Pasta de berenjena 100g', 0, 4, 228, 1, 20, 8, 1.80],
    ['Batido de proteinas', 0, 5, 160, 30, 3, 5, 4.00],
    ['Hamburguesa vegetariana 1', 0, 5, 220, 21, 12, 3, 3.00],
    ['Hamburguesa vegetariana 2', 0, 12, 165, 16, 9, 2, 2.80],
    ['Huevo cocido 1', 0, 8, 155, 13, 11, 1, 0.80],
    ['Huevo frito 1', 0, 16, 196, 14, 15, 1, 0.90],
    ['Medio baguette', 0, 3, 274, 10, 0, 52, 2.20],
    ['Pan tajado 1 tajada', 0, 3, 97, 3, 1, 17, 0.40],
    ['Pizza de queso1u', 0, 3, 903, 36, 47, 81, 6.00],
    ['Pizza vegetariana 1u', 0, 3, 766, 26, 35, 85, 5.50],
    ['Leche de soya 200ml', 0, 1, 115, 8, 4, 11, 1.50],
    ['Leche de soya achocolatada 250ml', 0, 3, 160, 7, 6, 20, 1.80],
]

df_productos = pd.DataFrame(datos_productos, columns=['Nombre', 'Min', 'Max', 'Cal', 'Prot', 'Grasa', 'Carb', 'Costo'])

# Metas exactas
cal_meta = 2500 * 7
prot_meta = (cal_meta * 0.3) / 4
grasa_meta = (cal_meta * 0.2) / 9
carb_meta = (cal_meta * 0.5) / 4

# ==========================================
# 2. CONSTRUCCIÓN DEL MODELO GUROBI
# ==========================================
# Suprimimos la salida estándar de Gurobi en consola para mayor limpieza
env = gp.Env(empty=True)
env.setParam('OutputFlag', 0)
env.start()

modelo = gp.Model("Optimizacion_Dieta", env=env)

# Variables de Decisión: Cantidad a comprar de cada producto (Debe ser un número Entero)
num_productos = len(df_productos)
x = modelo.addVars(num_productos, vtype=GRB.INTEGER, name="x")

# Establecer límites (Min y Max) directamente en las variables
for i in range(num_productos):
    x[i].lb = df_productos.loc[i, 'Min']
    x[i].ub = df_productos.loc[i, 'Max']

# Variables de Desviación (Goal Programming): Cuánto nos pasamos o nos falta por nutriente
d_cal_mas = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_cal_mas")
d_cal_menos = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_cal_menos")

d_prot_mas = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_prot_mas")
d_prot_menos = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_prot_menos")

d_grasa_mas = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_grasa_mas")
d_grasa_menos = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_grasa_menos")

d_carb_mas = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_carb_mas")
d_carb_menos = modelo.addVar(vtype=GRB.CONTINUOUS, name="d_carb_menos")

# ==========================================
# 3. RESTRICCIONES (Ecuaciones de Balance)
# ==========================================
# Total consumido - Lo que sobra + Lo que falta = Meta
modelo.addConstr(gp.quicksum(df_productos.loc[i, 'Cal'] * x[i] for i in range(num_productos)) - d_cal_mas + d_cal_menos == cal_meta, "Balance_Calorias")
modelo.addConstr(gp.quicksum(df_productos.loc[i, 'Prot'] * x[i] for i in range(num_productos)) - d_prot_mas + d_prot_menos == prot_meta, "Balance_Proteinas")
modelo.addConstr(gp.quicksum(df_productos.loc[i, 'Grasa'] * x[i] for i in range(num_productos)) - d_grasa_mas + d_grasa_menos == grasa_meta, "Balance_Grasas")
modelo.addConstr(gp.quicksum(df_productos.loc[i, 'Carb'] * x[i] for i in range(num_productos)) - d_carb_mas + d_carb_menos == carb_meta, "Balance_Carbohidratos")

# Ecuación de Costo Total
costo_total = gp.quicksum(df_productos.loc[i, 'Costo'] * x[i] for i in range(num_productos))

# ==========================================
# 4. FUNCIÓN OBJETIVO
# ==========================================
# Queremos minimizar el Costo Total, pero penalizando fuertemente si no cumplimos las metas nutricionales
# Multiplicamos las desviaciones por una "Multa" (M) muy alta para que Gurobi priorice la salud antes que el ahorro.
M = 50
penalizacion = M * (d_cal_mas + d_cal_menos + d_prot_mas + d_prot_menos + d_grasa_mas + d_grasa_menos + d_carb_mas + d_carb_menos)

modelo.setObjective(costo_total + penalizacion, GRB.MINIMIZE)

# ==========================================
# 5. RESOLUCIÓN Y RESULTADOS
# ==========================================
modelo.optimize()

if modelo.status == GRB.OPTIMAL:
    print("=== RESOLUCIÓN EXACTA (GUROBI) ===")
    costo_real = sum(df_productos.loc[i, 'Costo'] * x[i].X for i in range(num_productos))

    # Extraer las cantidades óptimas
    cantidades_optimas = [int(x[i].X) for i in range(num_productos)]
    df_productos['Cantidad_Gurobi'] = cantidades_optimas

    print(f"Costo Total de la Dieta (Semanal): ${costo_real:.2f}")

    # Evaluar qué tan lejos quedamos de las metas
    cal_logradas = sum(df_productos.loc[i, 'Cal'] * cantidades_optimas[i] for i in range(num_productos))
    print(f"Calorías logradas: {cal_logradas:.0f} / Meta: {cal_meta}")

    print("\nLista de Compras Óptima:")
    display(df_productos[df_productos['Cantidad_Gurobi'] > 0][['Nombre', 'Cantidad_Gurobi', 'Costo']])
else:
    print("El modelo no encontró una solución óptima factible.")

Collecting gurobipy
  Downloading gurobipy-13.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (16 kB)
Downloading gurobipy-13.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (14.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 70.5 MB/s eta 0:00:00
Installing collected packages: gurobipy
Successfully installed gurobipy-13.0.1
=== RESOLUCIÓN EXACTA (GUROBI) ===
Costo Total de la Dieta (Semanal): $179.45
Calorías logradas: 17501 / Meta: 17500

Lista de Compras Óptima:

                              Nombre  Cantidad_Gurobi  Costo
0                          Banano 1u                4   0.50
1                       Mandarina 1u                3   0.30
2                          Piña 100g                7   0.75
3                          Uvas 100g                7   1.20
4                    Chocolate 1 bar                4   2.00
5                   Queso Paipa 100g                8   3.50
10               Batido de proteinas                5   4.00
11         Hamburguesa vegetariana 1                5   3.00
12         Hamburguesa vegetariana 2               12   2.80
13                    Huevo cocido 1                8   0.80
14                     Huevo frito 1                3   0.90
15                    Medio baguette                3   2.20
16               Pan tajado 1 tajada                3   0.40
17                  Pizza de queso1u                3   6.00
18              Pizza vegetariana 1u                3   5.50
19               Leche de soya 200ml                1   1.50
20  Leche de soya achocolatada 250ml                3   1.80